#!/usr/bin/env sh

# Edit parameters here, then run:
#   sh validate_data/run_validate_hdf5.sh

PYTHON_BIN="${PYTHON_BIN:-python3}"

# Choose one of: pointcloud, tcp, both
RUN_TARGET="pointcloud"

# HDF5 file generated by postprocess/convert_hdf5.py.
HDF5="/home/xense/flexiv_rizon4s_workspace/Train_Data/pick_test.hdf5"

# Demo group under /data. Leave empty to use the first sorted demo.
DEMO=""

# Point-cloud visualization options.
POINTCLOUD_FPS="10"
POINTCLOUD_START_FRAME="0"
POINTCLOUD_STRIDE="1"
POINTCLOUD_POINT_SIZE="2.0"
POINTCLOUD_COORD_FRAME="camera"
# Leave empty to use Data_Collect/calib/data/extrinsics.txt.
POINTCLOUD_CAMERA_C2W=""
POINTCLOUD_LOOP="false"
POINTCLOUD_NO_COLOR="false"
POINTCLOUD_SUMMARY_ONLY="false"

# TCP replay options.
TCP_DATA_GROUP="data"
TCP_START="0"
TCP_END=""
TCP_STRIDE="1"
TCP_FPS="30"
TCP_SETTLE_STEPS="8"
TCP_DRIVE_MODE="position"
TCP_IK_ITERATIONS="150"
TCP_IK_RESIDUAL_THRESHOLD="1e-5"
TCP_WIDTH_TO_FINGER_SCALE="0.5"
TCP_DIRECT="false"
TCP_LOOP="false"
TCP_HOLD="true"
TCP_NO_PLANE="false"
TCP_NO_PATH="false"

# Robot/kinematics resources.
# Leave R3KIT_ROOT empty to use ../Ref/r3kit relative to Data_Collect.
R3KIT_ROOT="/home/xense/flexiv_rizon4s_workspace/Data_Collect/submodule/r3kit"

# Leave URDF empty to use validate_data/urdf/Flexiv Rizon4s Xense/flexiv_Rizon4s_kinematics.urdf.
# If your URDF is elsewhere, set it explicitly.
URDF="/home/xense/flexiv_rizon4s_workspace/Train_Data/urdf/Flexiv Rizon4s Xense/flexiv_Rizon4s_kinematics.urdf"
EE_LINK="xense_hand"
BASE_X="0.0"
BASE_Y="0.0"
BASE_Z="0.0"
BASE_ROLL="0.0"
BASE_PITCH="0.0"
BASE_YAW="0.0"

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
DATA_COLLECT_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
PROJECT_3D_ROOT=$(CDPATH= cd -- "$DATA_COLLECT_ROOT/.." && pwd)

if [ -z "$R3KIT_ROOT" ]; then
  R3KIT_ROOT="$PROJECT_3D_ROOT/Ref/r3kit"
fi

if [ -z "$URDF" ]; then
  URDF="$SCRIPT_DIR/urdf/Flexiv Rizon4s Xense/flexiv_Rizon4s_kinematics.urdf"
fi

print_command() {
  printf 'Running:'
  printf ' %s' "$PYTHON_BIN"
  for arg in "$@"; do
    printf ' %s' "$arg"
  done
  printf '\n\n'
}

check_hdf5() {
  if [ -z "$HDF5" ] || [ "$HDF5" = "/path/to/train_data.hdf5" ]; then
    echo "Please edit HDF5 in validate_data/run_validate_hdf5.sh first."
    exit 1
  fi
}

check_tcp_resources() {
  if [ ! -d "$R3KIT_ROOT/r3kit" ]; then
    echo "r3kit package was not found: $R3KIT_ROOT/r3kit"
    echo "Edit R3KIT_ROOT in validate_data/run_validate_hdf5.sh."
    exit 1
  fi

  if [ ! -f "$URDF" ]; then
    echo "URDF file was not found: $URDF"
    echo "Edit URDF in validate_data/run_validate_hdf5.sh."
    exit 1
  fi
}

run_pointcloud() {
  set -- \
    "$SCRIPT_DIR/visualize_hdf5_pointcloud.py" \
    --hdf5 "$HDF5" \
    --fps "$POINTCLOUD_FPS" \
    --start-frame "$POINTCLOUD_START_FRAME" \
    --stride "$POINTCLOUD_STRIDE" \
    --point-size "$POINTCLOUD_POINT_SIZE" \
    --coord-frame "$POINTCLOUD_COORD_FRAME"

  if [ -n "$DEMO" ]; then
    set -- "$@" --demo "$DEMO"
  fi

  if [ -n "$POINTCLOUD_CAMERA_C2W" ]; then
    set -- "$@" --camera-c2w "$POINTCLOUD_CAMERA_C2W"
  fi

  if [ "$POINTCLOUD_LOOP" = "true" ]; then
    set -- "$@" --loop
  fi

  if [ "$POINTCLOUD_NO_COLOR" = "true" ]; then
    set -- "$@" --no-color
  fi

  if [ "$POINTCLOUD_SUMMARY_ONLY" = "true" ]; then
    set -- "$@" --summary-only
  fi

  print_command "$@"
  "$PYTHON_BIN" "$@"
}

run_tcp() {
  set -- \
    "$SCRIPT_DIR/replay_hdf5_tcp_pybullet.py" \
    --hdf5 "$HDF5" \
    --data-group "$TCP_DATA_GROUP" \
    --urdf "$URDF" \
    --ee-link "$EE_LINK" \
    --base-pos "$BASE_X" "$BASE_Y" "$BASE_Z" \
    --base-rpy "$BASE_ROLL" "$BASE_PITCH" "$BASE_YAW" \
    --start "$TCP_START" \
    --stride "$TCP_STRIDE" \
    --fps "$TCP_FPS" \
    --settle-steps "$TCP_SETTLE_STEPS" \
    --drive-mode "$TCP_DRIVE_MODE" \
    --ik-iterations "$TCP_IK_ITERATIONS" \
    --ik-residual-threshold "$TCP_IK_RESIDUAL_THRESHOLD" \
    --width-to-finger-scale "$TCP_WIDTH_TO_FINGER_SCALE" \
    --r3kit-root "$R3KIT_ROOT"

  if [ -n "$DEMO" ]; then
    set -- "$@" --demo "$DEMO"
  fi

  if [ -n "$TCP_END" ]; then
    set -- "$@" --end "$TCP_END"
  fi

  if [ "$TCP_DIRECT" = "true" ]; then
    set -- "$@" --direct
  fi

  if [ "$TCP_LOOP" = "true" ]; then
    set -- "$@" --loop
  fi

  if [ "$TCP_HOLD" = "true" ]; then
    set -- "$@" --hold
  fi

  if [ "$TCP_NO_PLANE" = "true" ]; then
    set -- "$@" --no-plane
  fi

  if [ "$TCP_NO_PATH" = "true" ]; then
    set -- "$@" --no-path
  fi

  print_command "$@"
  "$PYTHON_BIN" "$@"
}

check_hdf5
cd "$DATA_COLLECT_ROOT" || exit 1

case "$RUN_TARGET" in
  pointcloud)
    run_pointcloud
    ;;
  tcp)
    check_tcp_resources
    run_tcp
    ;;
  both)
    run_pointcloud
    check_tcp_resources
    run_tcp
    ;;
  *)
    echo "Unknown RUN_TARGET: $RUN_TARGET"
    echo "Expected one of: pointcloud, tcp, both"
    exit 1
    ;;
esac
